### ISSUE TITLE
Parameters for INRIA dataset

### ISSUE THREAD

**Issue by raphaelsulzer** [HeinzJiao/PolyR-CNN#6]
Hi and thank you for making this nice work available here.

I am trying to train your method on the INRIA dataset. Your paper mentions that you crop the 5000x5000 images to 512x512 patches, similar to HiSup. In `preprocess_annotations.json` is seems like that the image size is set to 300 px. Do I just change that to 512 px to preprocess the INRIA dataset? Further, the swin transformer backbone takes images of size 224x224 if I am not mistaken. Do you just resize / downsample the cropped INRIA images to this size? 

Besides the image size, your paper mentions that you use unified vertex number per polygon `M=50` for the INRIA dataset. If I set `M=50` during preprocessing, I later get an error  somewhere in your forward pass. What should I use?

**Comment by raphaelsulzer** [comment]
I trained a model with the config below. Even after 100 epochs the loss_polygon is around 10, loss_gio around 0.3 and loss_cor around 2. 

Below some predictions on the validation set produced with the demo.py (I slightly changed the visualisation).

Any idea what could have gone wrong? Or are those the expected results?

![Image](https://github.com/user-attachments/assets/51d46e8a-7c90-4e7c-ad63-a1af0904f0a1)
![Image](https://github.com/user-attachments/assets/62140032-ec81-4e6a-b288-b65698ec8bf5)

```
_BASE_: "Base-PolyRCNN.yaml"
DATALOADER:
  NUM_WORKERS: 1
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  PolyRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("inria_train",)  # 89280 images in total (outer polys), 10908 images in total (inner polys)
  TEST:  ("inria_val",)
SOLVER:
  STEPS: (60698, 68200)  # 89th epoch
  MAX_ITER: 68201  # 100th epoch
  CHECKPOINT_PERIOD: 682  # save checkpoint per epoch
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 1000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
```
